Squashed 'Sources/ASIO/' changes from dc67374fc..147f7225a
147f7225a asio version 1.24.0 released
b3f4dbc57 Revision history.
75228f953 Regenerate platform macros documentation.
4f1dea34e Remove hardcoded path.
d0f44c8d0 Change MSVC version used for system_error workaround.
4709210bc Recreate the select_reactor's interrupter on a user-supplied thread, when using IOCP on Windows.
4962dce7e Boostify the quick reference.
e190fe866 Store reference to basic_yield_context in handler.
26ab3309b Destroy spawned thread immediately if it completes within handler invocation.
656cc92de Defend against Qt macros when using Intel C++.
d3b79bfb6 Remove faulty assertions from experimental::coro implementation.
736a3a2c3 Fix detection of aligned_alloc for Apple platforms.
879dab6e8 Change async_compose example to use return type compatible with new async_result form.
10251c3a9 Avoid copying async operation object in await_transform.
6461f0d7c Disable index_sequence emulation when variadic templates are unavailable.
4915cfd8a asio version 1.23.0 released
03a119e66 Revision history.
05f0a472c Add pkg-config support.
6d5149057 Make standard library feature macros available.
9902fe7d1 Fix usage of macro to detect std::exception_ptr.
15d662c27 Use deferred rather than use_awaitable in awaitable_operators implementation.
43a1d4738 Fix compatibility with older compilers.
2db709458 Use local implementation of soon-to-be-deprecated std::aligned_storage.
b57695124 Regenerate documentation.
d9afe3539 Require at least gcc 7.4 to enable aligned_alloc.
79e97f06c Add coroutines examples for C++20.
0331e5a7a Add composed operation examples for c++20.
34fce9b8f Correctly mark compile-only test cases.
ed929893b Use void* for socket address to match documented Endpoint requirements.
8ffc8545d Add missing release() member functions to windows overlapped handles.
3ed8ead67 Add missing release() member functions to pipes.
bb8bafc3a Add missing throw-if-cancelled check when awaiting an async op directly.
a4df2acc0 Fix -Wmaybe-uninitialized warnings.
6298e2780 Propagate exceptions from awaited initiation functions through the resuming handler.
1f6f47f5a Specifically exclude forced_unwind exceptions from catch-all.
292861e67 Update C++11 timeouts example to use new form of async_result.
4ff4256e2 Ensure all operations examples use the new async_result form.
5302adea0 Obtain associated allocator before handler is moved.
836206b71 Fix missing include.
9f250bfb5 Update FreeBSD version for CI.
6d48fccb2 Removed all & race from promise - parallel_group covers most of it now.
34389f4e9 Fix issue where parallel_group initiation incorrectly moved arguments instead of forwarding them.
8f6e2d4c3 Fix detection of invoke_result for clang/libc++.
64c7dc2cc Fix error location for windows overlapped and handle operations.
7073e5366 Regenerate documentation.
8606891e2 Add converting move construction/assignment to pipes.
67bdae56d Add converting move construction/assignment to serial ports.
322f31195 Add tests for converting move construction/assignment of files.
87da4dcc5 Add converting move construction/assignment to Windows stream and random-access handles.
53f99df3f Add converting move construction/assignment to Windows object_handle.
8a6a6f3ec Add converting move construction/assignment to posix descriptors.
c318b232d Optimise move construction of I/O objects where only the executor type differs.
f8dca00d8 Code formatting.
7fd8033c2 Fix there is no warning number 'XXXX' in windows.
566bda276 Explicitly state that shutdown(what) calls are thread-safe.
4de8e6dab Make gcc_x86_fenced_block compatible with -masm=intel.
ef4c4f337 Regenerate documentation.
939f25a9e Change spawn() to be a completion token-based async operation.
eed90ae8d Fix compatibility with OpenSSL 3.0.4 and later.
3953c82c9 Allow awaitable<>-based coroutines to directly co_await operations.
859b5a987 Use completion_signature_of in implementation of experimental::parallel_group.
4c999af63 Use completion_signature_of in implementation of deferred.
28e14e400 Add completion_signature_of trait.
f5abcf9f5 Add is_async_operation trait and async_operation concept.
cb26a5df0 Add buffer() overloads for contiguous containers, such as std::span.
f7faa79cf Add source location to error codes, when using Boost.
f64a25655 Add source locations to exceptions, when using Boost.
02e812a44 Use separate function to clear error codes.
1dde86f03 Move deferred to the asio namespace.
4d78f52f5 Move prepend to the asio namespace.
12c886970 Move append to the asio namespace.
5175f9082 Move as_tuple to the asio namespace.
4d36f3087 Make experimental::parallel_group compatible with C++11.
bd8f2ce6b Make experimental::prepend compatible with C++11.
8913db15c Make experimental::append compatible with C++11.
a4bf936e4 Make experimental::deferred compatible with C++11.
4e622703e Use a trailing return type with decltype on initiating functions for C++11.
93e3c81d5 asio version 1.22.2 released
241757e31 Ensure c++20 examples are included in tarball.
1e57de9ca Revision history.
70afbd3a6 Regenerate documentation.
aa74107db Add channels to the overview.
895bb7d0b Note that I/O object constructors are passed executors or execution contexts.
1ae578b3f Work around code formatting problem in doc generation.
1421850fc Add completion token cross-references to tutorial.
f0a1e1c7c Dispatch co_spawn cancellation through the executor, if the completion handler specifies its own associated executor.
6a509b20a Fix reset() so that it works on an unclosed channel.
d505fa221 For UNIX domain sockets on linux, connect() may yield EAGAIN to indicate an in-progress operation.
b2e7ba6c1 Change promise to copy executor from first item before moving range.
4823bd285 On Windows, use same share mode as files opened via fopen().
d36734b97 Add completion token cross-references.
6f9b3abf0 Remove broken wiki link.
42026cdd6 Update platform macros documentation.
d76506231 Exclude boostify comment markers.
582a723c0 Add experimental::promise to the overview.
20f099944 Add async_compose to the overview.
a862abd94 Update timer overview in terms of waitable timers.
b74c6514f Add pipes to overview.
0913c24ba Add files to overview.
29599ba5e Add completion token adapters to the overview.
9ad917601 Add experimental::parallel_group to the overview.
fbc4f27b9 Add experimental::deferred to the overview.
d625f9a91 Move 'Futures' to 'Composition and Completion Tokens' section.
e49a01810 Regenerate documentation.
919860adf Fix cross-reference to co_spawn.
8d07803f4 Additional documentation for channels.
e776841ae Additional documentation for ip::address_v6.
b21d47a07 Additional documentation for ip::address_v4.
49f56e2e1 Revert to using executor_work_guard in io_context documentation.
ba2a01d91 Additional documentation for make_work_guard.
90ad90a26 Additional documentation for make_strand.
bba12d105 asio version 1.22.1 released
654ff9ebd Revision history.
b89fcb895 Fix memory management in experimental::promise's type-erased completion handlers.
f48b6972d Clear coro's cancellation slot at completion of each operation.
b4ebe88f4 Add C++14 examples of wrapping callback-based APIs.
951def5dd Explicitly check io_uring is not the default before registering with reactor.
8c1e3e4e3 Fix circular inclusion issue.
451e4bd87 Fix argument order in io_uring implementation of write_some_at.
3d46fa235 Fix links to file descriptor passing examples on examples page.
95f680b88 Update Handler requirements.
40fa3f07b Update requirements on asynchronous operations.
dc02d0d64 Fix broken doc link.
ca329d1c8 Revert accidental change to ssl example.
be6c239d9 Update documentation for dispatch, post, and defer.
1a49c08ed Clarify the non-concurrency guarantees made for allocators.
04c6c2fc3 Include 'func' in if-test, as it was accidentally removed in 10f5ed3f035616af1fbd2e865f9e429c636eaa46.
18bf1ca67 Expose recycling_allocator as part of public interface.
21ea741cf Use default alignment as minimum alignment for allocations.
4d0697760 Work around shutdown ordering issue in coro/executor test.
2fad4dee3 Translate system errors returned by openssl 3.0 or later.
50d6d365d Don't use deprecated RSA-specific functions for openssl 3.0 or later.
10f5ed3f0 Don't use ERR_func_error_string for openssl 3.0 or later.
caebf3101 Remove DH struct usage for OpenSSL 3.0+.
f79d3dc5c Fix variable reference in sockatmark().
ac57d4cd6 Fix file format.
480d9c3b9 Rework reference documentation in terms of completion tokens.
8abb513c7 Document per-operation cancellation for serial ports.
ec61fe3d0 Add cancellation_slot support to signal sets.
54a8ac0ab Enable movable iostreams for clang.
383dbdaa4 Add overview of asynchronous model.
fc901d79c Add workaround for apparent coroutine codegen bug with Apple's clang.
177a5e851 Mark dynamic_buffer() result as nodiscard.
ad5cfd24a Mark buffer() result as nodiscard.
f336c0cb6 Fix promise.hpp: 'all_of': is not a member of 'std'.
7ae347e1f Header <utility> is needed for std::exchange.
0bbe46496 Mark experimental::make_parallel_group() result as nodiscard.
baace6088 Mark experimental::prepend() result as nodiscard.
788b596df Mark experimental::append() result as nodiscard.
1ad641416 Mark experimental::as_tuple() result as nodiscard.
d73ce6908 Mark experimental::as_single() result as nodiscard.
cfc575fb1 Mark get_associated_cancellation_slot() result as nodiscard.
34a7c2314 Mark get_associated_executor() result as nodiscard.
9c77dc6ab Mark get_associated_allocator() result as nodiscard.
e2c83c004 Mark make_work_guard() result as nodiscard.
7db04869d Mark bind_cancellation_slot() result as nodiscard.
155305ca2 Mark bind_allocator() result as nodiscard.
1a2005f40 Mark bind_executor() result as nodiscard.
d5a18cab1 Fix "'this' pointer is null" warnings.
8869d25ae Remove unused lambda capture.
f97a1bb52 Fix deprecated enum usage warning.
bace22412 Add missing include of asio/error_code.hpp.
3da0ef20f Add file_base::sync_all_on_write flag.
f5ea17dea Document 'Completion Signature' for each asynchronous operation.
d9e1af5b9 Add example showing file descriptor passing over local sockets.
46bc82197 Add support for adopting an existing SSL* into an ssl::stream<>.
adec14892 Fix any_io_executor with ASIO_USE_TS_EXECUTOR_AS_DEFAULT and ASIO_SEPARATE_COMPILATION.
f90289638 Fix bind_cancellation_slot compatibility with legacy completion tokens.
c70a453e2 Fix bind_executor compatibility with legacy completion tokens.
e92c9274d Enable executor_work_guard<> even when ASIO_NO_TS_EXECUTORS is defined.
af6ebcdd0 Add missing implementation of basic_file::release().
32f971346 Add unit test for experimental::as_tuple.
02b6b50a3 Fix small typo in documentation for ip::v6_only socket option.
42c5362d9 Fix move operator= for stream_core.
38ba862ad Fix missing reference to sender_endpoint in io_uring_socket_recvfrom_op.
777022386 Fixed detail::has_allocator_type<T> not matching T::allocator_type
7923149ab Add bind_allocator.
5f91c3083 Include detail/concurrency_hint.hpp from io_context.hpp.
5c40aa5cb Fix 'zero as null pointer constant' warning.
81f7342a3 Fix associator specialisations for append and prepend.
4b6f2c8cf Update copyright notices.
0d4e89a14 asio version 1.22.0 released
036fa8c5f Revision history.
bdbe4b5b7 Link to channels example from documentation.
607b67c75 Fix awaitable move operator return value.
5584f7386 Make awaitable_operators.hpp self contained
f70f65ae5 Use default 'new' alignment, if available.
afb971ba8 Eliminate shared_ptr from coro co_spawn() implementation.
fa4bac545 Prevent async_resume from being called on coro temporaries.
51d74ca77 Regenerate documentation.
689cf69e1 Fix any_io_executor with ASIO_USE_TS_EXECUTOR_AS_DEFAULT.
4950d6db7 Work around header inclusion order problem when io_uring is enabled.
9fa7cc752 Fix shutdown cleanup issue in experimental::parallel_group.
c3df3cb1a Add overview documentation for error handling with C++20 coroutines.
1e48957b4 Clean up coro overview.
9f33d210f Ensure ASIO_EXECUTION_EXECUTOR macro does not appear in generated docs.
ad78173e5 Add clarifications to concurrency hint documentation.
ad6655b23 Add missing move assignment operator to awaitable<>.
4a232888a Regenerate certificates for ssl examples.
8d45e8389 Fix bind_executor so that it doesn't require a token to provide legacy async_result support.
0c2d87189 Include library and function in ssl error strings.
9c9208a8d Fully qualify use of asio::error namespace.
92b2394fb Add channel-based proxy example.
2ac154d44 Fix linked list corruption in channel cancel/close handling.
ea8555795 Add missing destructors.
08a7029cb asio version 1.21.0 released
14407993e Revision history.
d0281ad84 Add experimental support for channels.
23c62e135 Fix clang-11 compile error when io_uring is enabled.
e7ae074cd Improvements to asio::experimental::coro.
92aacba13 Disable aligned_alloc on clang when using MSVC runtime.
31de5cd67 Use faster implementation for network_v4::canonical().
55a081517 Fix gcc shadow warnings.
5680b35c2 Remove spurious include.
e87571949 Add missing file synchronisation functions.
51d5bb3d4 Regenerate documentation.
dc121e238 Add support for registered buffers.
ee6ed5b1f Enable io_uring backend for pipes.
dafcc4a0a Only use io_uring for sockets if it's the default backend.
8faefdeb5 Only use io_uring for descriptors if it's the default backend.
435252b20 Regenerate documentation.
f2158f539 Add missing documentation for parameter.
6053265e2 Add support for portable pipes.
2a07c5bb6 Add support for files.
36440a92e Add io_uring backend.
1da17dd64 Decouple the scheduler from the concrete task type.
b725b7d17 Revert "Don't use shared_ptr in basic_socket_streambuf implementation."
a457dc413 Increase small object buffer size for any_executor.
3e33d7a3c Reduce size of io_context executors to a single pointer.
55435a0e8 Update minimum ubuntu to 18.04.
5d6dd8695 Remove inclusion of boost/scope_exit.hpp.
32e253c30 Fix multi-signature handling when variadic templates are disabled.
e2ceafeb7 Disable separate compilation in MinGW test runners.
95da1e1ad Add execution::is_executor<> specialisations for non-executors.
ad8617cbf Add empty explicit specialisation of is_valid_target_executor<int, ...>.
f3aa8580d Enable separate compilation for cancellation_signal/slot.
bae9bcf56 Enable separate compilation for any_io_executor.
68608ffbf Don't use shared_ptr in basic_socket_streambuf implementation.
7e9c986e6 Add empty explicit specialisation composed_work_guard<system_executor>.
b3a03038c Enable ASIO_HAS_STD_INVOKE_RESULT with libc++13.
8d0b41cd9 Disable non-virtual destructor warning on MSVC.
cd68912b7 Fix the initialisation order of members.
0997e432e Fix typo in io_context documentation (overlaod -> overload).
7d88fa68d Fix compilation on Solaris.
470ee8bea Fix defence against macros defined by Qt on MSVC.
498dd977d Fixes compiler error "error: 'asio::posix' has not been declared" on Windows 10 with MSYS Mingw64 10.3.0
97e52f100 Use declval in is_legacy_connect_condition check.
6c054e98f asio version 1.20.0 released
f5af73cc6 Revision history.
d038fb3c2 Document per-operation cancellation for coroutines.
33414293a Add documentation for parallel_group.
bc5cdb1a4 Add experimental::coro to overview.
cb04aa612 Synchronise overview TOC with Boost.Asio version.
0fd3cf3dd Add missing C++14 examples.
38b29be6d Add documentation for per-operation cancellation.
46a7dfdb8 Update C++20 coroutines overview.
d1ccf2ec2 Gcc fixes for promise & coro.

git-subtree-dir: Sources/ASIO
git-subtree-split: 147f7225a96d45a2807a64e443177f621844e51c